version: '3'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - dbdata:/var/lib/sqlite
    ports:
      - "8000:8000"

volumes:
  dbdata:
